services:
  backend:
    build: ./user_service/.
    container_name: user_service
    restart: always
    volumes:
      - ./:/usr/app/user_service/.
    working_dir: /usr/app/user_service/.
    ports:
      - "8080:8080"
    command: bash -c 'python -m user_service.src.app.main'
    networks:
      - app_network
    expose:
      - 8080

networks:
  app_network: