services:
  backend-service:
    build: ./backend/.
    container_name: backend-service
    environment:
      - ALEMBIC_CONFIG=/usr/backend_app/backend/alembic.ini
    volumes:
      - ./:/usr/backend_app/.
    working_dir: /usr/backend_app/.
    ports:
      - "8080:8080"
    command: bash -c 'alembic upgrade head && python -m backend.src'
    networks:
      - app-network
    expose:
      - 8080
    depends_on:
      - db-service

  db-service:
    image: postgres:latest
    container_name: db-service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    env_file:
      - ./backend.env
    ports:
      - 5432:5432
    expose:
      - 5432

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yaml"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file:
      - ./ngrok.env
    volumes:
      - ./ngrok/settings.yaml:/etc/ngrok.yaml
    ports:
      - 4040:4040
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
