services:
  postgres:
    profiles: [ "api", "migrations" ]
    image: postgres:latest
    container_name: api.pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_root:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - api.network.pg
    env_file:
      - .env

  api:
    profiles: [ "api" ]
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api.network
      - api.network.pg
    volumes:
      - ./src:/usr/api/src
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  migrations:
    profiles: [ "migrations" ]
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.pg.migrations
    volumes:
      - ./src/fastapi_example/infrastructure/database/migrations/versions:/usr/api/src/fastapi_example/infrastructure/database/migrations/versions
      - ./alembic.ini:/usr/api/alembic.ini:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api.network.pg
    command: ["uv", "run", "alembic", "upgrade", "head"]
    env_file:
      - .env

  grafana:
    profiles: [ "monitoring" ]
    image: grafana/grafana:latest
    container_name: api.monitoring.grafana
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/datasourses/grafana-config.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana.data:/var/lib/grafana:rw
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
    networks:
      - api.network.monitoring

  loki:
    profiles: [ "monitoring" ]
    image: grafana/loki:latest
    container_name: api.monitoring.loki
    hostname: api.monitoring.loki
    expose:
      - "3100"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki.data:/tmp/:rw
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    networks:
      - api.network.monitoring

  promtail:
    profiles: [ "monitoring" ]
    image: grafana/promtail:3.0.0
    container_name: api.monitoring.promtail
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - api.network.monitoring

volumes:
  pg_root:
  loki.data:
  grafana.data:

networks:
  api.network:
    name: api.network
    driver: bridge
  api.network.pg:
    name: api.network.pg
  api.network.monitoring:
    name: api.network.monitoring
