[pytest]
testpaths = test/unit

python_files = test_*.py
python_classes = Test*
python_functions = test_*

minversion = 8.0

asyncio_mode = auto

addopts = 
    -v
    --strict-markers
    --tb=short
    --cov=src/fastapi_example
    --cov-report=html
    --cov-report=term-missing

markers =
    asyncio
    unit
    integration
