from typing import Any, Protocol
from src.domain.entities.user import User
from src.application.dto import CreateUserDTO

class IUserMapper(Protocol):
    def domain_to_persistence(self, domain_user: User) -> Any: ...
    def persistence_to_domain(self, persistence_user: Any) -> User: ...
    def dto_to_persistence(self, dto: CreateUserDTO) -> Any: ...
